version: '3.1'

services:     
  # backend:
  #   build: ./backend/
  #   container_name: crud-api
  #   depends_on:
  #     - db                
  #   ports: 
  #       - 3000:3000          
  #   environment:
  #     - DB_HOST=db
  #     - DB_USERNAME=root
  #     - DB_PASSWORD=Mysql!
  #     - DB_DATABASE=device_mgmt
  #     - DB_PORT=3306
  #     - WAIT_HOSTS=db:3306
  #   volumes:
  #     - ./backend/:/src/
  #   networks:
  #     - app-network   
  
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql!
      - MYSQL_DATABASE=device_mgmt
    ports:
      - "3306:3306"
    volumes:
      - ./database/data:/var/lib/mysql    
  
  # app:
  #   build: ./frontend/
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - app-network  

networks:
  app-network:
    driver: bridge