version: '3.8'

services:   
  db:
    image: mysql:5.7
    container_name: device-mgmt-db
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql!
      - MYSQL_DATABASE=device_mgmt
    ports:
      - "3306:3306"
    volumes:
      - ./database/data:/var/lib/mysql    
    networks:
      - app-network  

  backend:
    build: ./backend/
    container_name: device-mgmt-api
    depends_on:
      - db                
    ports: 
        - 3333:3333
    volumes:
      - ./backend/:/usr/src/api    
    networks:
      - app-network 

  app:
    build: ./frontend/
    container_name: device-mgmt-app
    depends_on:
      - backend 
    ports:
      - 4200:4200
    volumes:
      - ./frontend/:/app/
    command: npm start
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge